# Generated by Django 2.0.5 on 2018-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf', verbose_name='报名表')),
                ('filename', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='MD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='姓名')),
                ('ug', models.CharField(max_length=50)),
                ('ument', models.CharField(max_length=50)),
                ('ufangxiang', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img')),
                ('jg', models.CharField(max_length=50)),
                ('minzu', models.CharField(max_length=50)),
                ('zzmm', models.CharField(max_length=50)),
                ('topxl', models.CharField(max_length=50)),
                ('topxw', models.CharField(max_length=50)),
                ('gym', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Ewater', models.CharField(max_length=50)),
                ('nowwork', models.CharField(max_length=100)),
                ('zhiwu', models.CharField(max_length=50)),
                ('jingli1', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli2', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli3', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli4', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli5', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli6', models.CharField(blank=True, max_length=200, null=True)),
                ('jingli7', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp1', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp2', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp3', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp4', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp5', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp6', models.CharField(blank=True, max_length=200, null=True)),
                ('jopexp7', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper1', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper2', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper3', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper4', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper5', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper6', models.CharField(blank=True, max_length=200, null=True)),
                ('Paper7', models.CharField(blank=True, max_length=200, null=True)),
                ('project1', models.CharField(blank=True, max_length=200, null=True)),
                ('project2', models.CharField(blank=True, max_length=200, null=True)),
                ('project3', models.CharField(blank=True, max_length=200, null=True)),
                ('project4', models.CharField(blank=True, max_length=200, null=True)),
                ('project5', models.CharField(blank=True, max_length=200, null=True)),
                ('project6', models.CharField(blank=True, max_length=200, null=True)),
                ('project7', models.CharField(blank=True, max_length=200, null=True)),
                ('reward1', models.CharField(blank=True, max_length=200, null=True)),
                ('reward2', models.CharField(blank=True, max_length=200, null=True)),
                ('reward3', models.CharField(blank=True, max_length=200, null=True)),
                ('reward4', models.CharField(blank=True, max_length=200, null=True)),
                ('reward5', models.CharField(blank=True, max_length=200, null=True)),
                ('reward6', models.CharField(blank=True, max_length=200, null=True)),
                ('reward7', models.CharField(blank=True, max_length=200, null=True)),
                ('reward8', models.CharField(blank=True, max_length=200, null=True)),
                ('reward9', models.CharField(blank=True, max_length=200, null=True)),
                ('reward10', models.CharField(blank=True, max_length=200, null=True)),
                ('textname', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
